# Generated by Django 4.1.5 on 2023-02-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('mark', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
