# Generated by Django 4.1.6 on 2023-02-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendation', '0002_mark_place_url_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
