# Generated by Django 4.1.7 on 2023-05-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendation', '0004_alter_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
