# Generated by Django 4.1.7 on 2023-05-28 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recomendation', '0005_mark_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='place_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recomendation.place'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
